---
title: "Comparison DXGs from downsampled 300 to all cells"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

#0. Load libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(openxlsx)
```

#1. Load data Human 

```{r}
# Make a list with data frame 
hdxg_path_all <- "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/Human_all/Suppl_Table_3_Shapley_t_test_human_DXG_nothresh.xlsx"

sheet_names <- getSheetNames(hdxg_path_all)
df_list <- lapply(sheet_names, function(sheet){
  read.xlsx(hdxg_path_all, sheet = sheet)
})

names(df_list) <- sheet_names

# make a subset containing the first entries
df_list_all_top <- lapply(df_list, function(df){
  rbind(head(df, 250), tail(df, 250))
})

names(df_list_all_top) <- sheet_names


# Now with the values from the subsetted analysis
path_folder <- "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/Human/"

hdxg_names_sub <- c(#AS
                    paste0(path_folder,"t_test_on_class_9_Human_Cardiomyocytes_AS_Human_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Endothelial_AS_Human_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Fibroblasts_AS_Human_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Immune.cells_AS_Human_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Neuro_AS_Human_Neuro_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Pericytes_AS_Human_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Human_Smooth.Muscle_AS_Human_Smooth.Muscle_CTRL.xlsx"),
                    #HFpEF
                    paste0(path_folder,"t_test_on_class_10_Human_Cardiomyocytes_HFpEF_Human_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Endothelial_HFpEF_Human_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Fibroblasts_HFpEF_Human_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Pericytes_HFpEF_Human_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Immune.cells_HFpEF_Human_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Smooth.Muscle_HFpEF_Human_Smooth.Muscle_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Human_Neuro_HFpEF_Human_Neuro_CTRL.xlsx"),
                    #HFrEF
                    paste0(path_folder,"t_test_on_class_11_Human_Cardiomyocytes_HFrEF_Human_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Endothelial_HFrEF_Human_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Fibroblasts_HFrEF_Human_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Pericytes_HFrEF_Human_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Immune.cells_HFrEF_Human_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Smooth.Muscle_HFrEF_Human_Smooth.Muscle_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Human_Neuro_HFrEF_Human_Neuro_CTRL.xlsx"))


df_list_sub <- lapply(hdxg_names_sub, function(file){
  read.xlsx(file)
})

names(df_list_sub) <- sheet_names

# make a subset containing the first entries
df_list_sub_top <- lapply(df_list_sub, function(df){
  rbind(head(df, 250), tail(df, 250))
})

names(df_list_sub_top) <- sheet_names

```

#2. Calculate Jaccard similarities of Features per comparison

```{r}
#Function for calculating Jaccard similarities

similarity_pct <- function(df1, df2){
  gene1 <- df1$Feature
  gene2 <- df2$Feature
  
  intersect_count <- length(intersect(gene1, gene2))
  union_count <- length(union(gene1, gene2))
  
  return((intersect_count/union_count * 100))
  
}

similarites_number <- sapply(names(df_list_sub_top), function(name){
  similarity_pct(df_list_all_top[[name]], df_list_sub_top[[name]])
})

similarity_df_h <- data.frame(Comparison = names(df_list_sub_top),
                            group_sim = c(rep("AS",7),
                                          rep("HFpEF", 7),
                                          rep("HFrEF", 7)),
                            JacSim = similarites_number)

similarity_df_h$celltype <- sapply(strsplit(similarity_df_h$Comparison, " "), `[`, 2)

```

# 3. Dot plot of similarities

```{r}
#Human
# Dotplot
p1 <- ggplot(similarity_df, aes(x=Comparison, y=JacSim, fill = celltype))+
  geom_point(shape=21, size=4, color="black", stroke = 0.4, alpha=0.8)+
  facet_wrap("group_sim", scales = "free_x", nrow=3, strip.position="top")+
  ylab("Jaccard similarity \n (in %)")+
  xlab("")+
  theme_classic()+
    theme(plot.title = element_text(face = "bold", color = "black", hjust = 0.5, size = 14),
          axis.title.y = element_text(face = "bold", color = "black", size = 14),
          axis.text.x = element_blank(),
          # axis.text.x = element_text(face = "bold", color = "black", angle = 45, hjust = 1, size = 14),
          axis.text.y = element_text(face = "bold", color = "black", hjust = 1, size = 14),
          legend.text = element_text(face = "bold", color = "black", size = 10),
          legend.title = element_text(face = "bold", color = "black", size = 14),
          legend.position = "right",
          strip.background = element_rect(fill = "grey90", color = NA),
          strip.text = element_text(face = "bold", size = 12))+
    scale_fill_manual(values = plot_colors)

guides.layer <- ggplot2::guides(fill = ggplot2::guide_legend(title = "Comparison",
                                                             title.position = "top",
                                                             title.hjust = 0.5,
                                                             label.position = "right",
                                                             keywidth = ggplot2::unit(0.2, "cm"),
                                                             keyheight = ggplot2::unit(0.5, "cm"),
                                                             order = 1))
p1 + guides.layer

ggsave(plot = p1, filename = "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/dotplot/Human_Jaccard_250topdown.svg", width = 6, height = 8)
```

# 4. Load data Mouse
```{r}
# Make a list with data frame 
mdxg_path_all <- "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/Mouse_all/Suppl_Table_5_Shapley_t_test_mice_DXG_nothresh.xlsx"

sheet_names <- getSheetNames(mdxg_path_all)
df_list <- lapply(sheet_names, function(sheet){
  read.xlsx(mdxg_path_all, sheet = sheet)
})

names(df_list) <- sheet_names

# make a subset containing the first entries
df_list_all_top <- lapply(df_list, function(df){
  rbind(head(df, 250), tail(df, 250))
})

names(df_list_all_top) <- sheet_names


# Now with the values from the subsetted analysis
path_folder <- "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/Mouse/"

mdxg_names_sub <- c(#HFpEF
                    paste0(path_folder,"t_test_on_class_10_Mice_Cardiomyocytes_HFpEF_Mice_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Endothelial_HFpEF_Mice_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Fibroblasts_HFpEF_Mice_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Immune.cells_HFpEF_Mice_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Neuro_HFpEF_Mice_Neuro_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Pericytes_HFpEF_Mice_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_10_Mice_Smooth.Muscle_HFpEF_Mice_Smooth.Muscle_CTRL.xlsx"),
                    #HFrEF
                    paste0(path_folder,"t_test_on_class_11_Mice_Cardiomyocytes_HFrEF_Mice_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Endothelial_HFrEF_Mice_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Fibroblasts_HFrEF_Mice_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Immune.cells_HFrEF_Mice_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Neuro_HFrEF_Mice_Neuro_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Pericytes_HFrEF_Mice_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_11_Mice_Smooth.Muscle_HFrEF_Mice_Smooth.Muscle_CTRL.xlsx"),
                    #AS
                    paste0(path_folder,"t_test_on_class_9_Mice_Cardiomyocytes_AS_Mice_Cardiomyocytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Endothelial_AS_Mice_Endothelial_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Fibroblasts_AS_Mice_Fibroblasts_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Immune.cells_AS_Mice_Immune.cells_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Neuro_AS_Mice_Neuro_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Pericytes_AS_Mice_Pericytes_CTRL.xlsx"),
                    paste0(path_folder,"t_test_on_class_9_Mice_Smooth.Muscle_AS_Mice_Smooth.Muscle_CTRL.xlsx"))


df_list_sub <- lapply(mdxg_names_sub, function(file){
  read.xlsx(file)
})

names(df_list_sub) <- sheet_names

# make a subset containing the first entries
df_list_sub_top <- lapply(df_list_sub, function(df){
  rbind(head(df, 250), tail(df, 250))
})

names(df_list_sub_top) <- sheet_names

```

#5. Mouse Calculate Jaccard similarities of Features per comparison

```{r}
#Function for calculating Jaccard similarities

# df1 <- read.xlsx(paste0(path_folder,"t_test_on_class_9_Mice_Pericytes_AS_Mice_Pericytes_CTRL.xlsx"))
# df1 <- rbind(head(df1, 250), tail(df1, 250))
# df2 <- read.xlsx(mdxg_path_all, sheet = "Mice_PC_AS_PC_CTRL")
# df2 <- rbind(head(df2, 250), tail(df2, 250))

similarity_pct <- function(df1, df2){
  gene1 <- df1$Feature
  gene2 <- df2$Feature
  
  intersect_count <- length(intersect(gene1, gene2))
  union_count <- length(union(gene1, gene2))
  
  return((intersect_count/union_count * 100))
  
}

similarites_number <- sapply(names(df_list_sub_top), function(name){
  similarity_pct(df_list_all_top[[name]], df_list_sub_top[[name]])
})

similarity_df_m <- data.frame(Comparison = names(df_list_sub_top),
                            group_sim = c(rep("HFpEF",7),
                                          rep("HFrEF", 7),
                                          rep("AS", 7)),
                            JacSim = similarites_number)

similarity_df_m$celltype <- sapply(strsplit(similarity_df_m$Comparison, "_"), `[`, 2)

#remove the excluded Neuro AS cluster
similarity_df_m <- similarity_df_m[similarity_df_m$Comparison != "Mice_NC_AS_NC_CTRL",]

```

#6. Mouse dot plot
```{r}
p1 <- ggplot(similarity_df, aes(x=Comparison, y=JacSim, fill = celltype))+
  geom_point(shape=21, size=4, color="black", stroke = 0.4, alpha=0.8)+
  facet_wrap("group_sim", scales = "free_x", nrow=3, strip.position="top")+
  ylab("Jaccard similarity \n (in %)")+
  xlab("")+
  theme_classic()+
    theme(plot.title = element_text(face = "bold", color = "black", hjust = 0.5, size = 14),
          axis.title.y = element_text(face = "bold", color = "black", size = 14),
          axis.text.x = element_blank(),
          # axis.text.x = element_text(face = "bold", color = "black", angle = 45, hjust = 1, size = 14),
          axis.text.y = element_text(face = "bold", color = "black", hjust = 1, size = 14),
          legend.text = element_text(face = "bold", color = "black", size = 10),
          legend.title = element_text(face = "bold", color = "black", size = 14),
          legend.position = "right",
          strip.background = element_rect(fill = "grey90", color = NA),
          strip.text = element_text(face = "bold", size = 12))+
    scale_fill_manual(values = plot_colors)

guides.layer <- ggplot2::guides(fill = ggplot2::guide_legend(title = "Comparison",
                                                             title.position = "top",
                                                             title.hjust = 0.5,
                                                             label.position = "right",
                                                             keywidth = ggplot2::unit(0.2, "cm"),
                                                             keyheight = ggplot2::unit(0.5, "cm"),
                                                             order = 1))
p1 + guides.layer

ggsave(plot = p1, filename = "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/dotplot/Mouse_Jaccard_250topdown.svg", width = 6, height = 8)




```

#7. Combined plot 
```{r}
similarity_df_h[["species"]] <- "human"
similarity_df_m[["species"]] <- "mouse"
similarity_df_comb <- rbind(similarity_df_h, similarity_df_m)


dot_colours <- c("maroon","#2F4F4F","#DAA520","#2F4F4F", "tomato", "#b35900", "#236e00", "#7ad500", "#881800", "#004655","#6fa9a9","#DAA520")

theme_box <- function(){
  theme_bw() +
    theme(
      panel.border = element_rect(colour = "black", fill = NA, size = 1),
      panel.grid.major = element_line(colour = "grey90", linetype = "dotted"),
      panel.grid.minor = element_line(colour = "grey90", linetype = "dotted"),
      axis.line = element_line(colour = "black"),
      #facet_grid colors
      strip.background = element_rect(fill = "lightgrey", colour = "black", size = 1),
      strip.text = element_text(colour = "black", size = 12)
    )
}



ggplot(similarity_df_comb, aes(x=group_sim, y=JacSim, shape=species, color=species))+
  geom_point(aes(shape=species, size=species), position = position_dodge(width = 0))+
  theme_box() +
  facet_grid(~celltype, scales = "free")+
  scale_color_manual(name="Species",
                     values =  dot_colours)+
  scale_shape_manual(name="Species",
                     values = c(17,16,15))+
  scale_size_manual(name="Species",
                    values = c(4,4,4))+
  ylim(75, max(similarity_df_comb$JacSim)*1.0)+
  labs(title = paste0("Comparison of original and downsampled DXGs"), y = "Jaccard similarity \n (in %)", hjust=0.5) +
  theme(axis.text.x = element_text(color = "black", size = 14,angle = 45,hjust = 1, family = "Helvetica"),
        # axis.text.x = element_blank(),
        axis.text.y = element_text(color = "black", size = 14, family = "Helvetica"),
        axis.title.x = element_blank(),
        axis.title = element_text(size = 14, color = "black", family = "Helvetica"),
        plot.title = element_text(size = 14, hjust = 0, face ="bold", family = "Helvetica"),
        axis.line = element_line(color = "black"),
        strip.text.x = element_text(size = 14, color = "black", family = "Helvetica"),
        legend.text = element_text(size = 10, color = "black", family = "Helvetica"),
        legend.title = element_text(size = 10, color = "black", family = "Helvetica", face = "bold", hjust =0.5),
        panel.spacing = unit(0, "lines"))

ggsave("/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/PaperExternRevision/250807_Downsample_shapley_DXGs/dotplot/Comparison_of_original_and_downsampled_DXGs_250_TopDown.svg", width = 8.5, height = 3)

```


