---
title: "NN Paper Final Script: Logistic regression model on training data"
author: "Mariano Ruz Jurado"
date: "2024-08-14"
output: html_document
editor_options: 
  chunk_output_type: console
---

#1. Real run LGR model for each of the three big groups ( species, disease, cell type)
```{r}

library(glmnet)
library(data.table)
library(tidyverse)

# Load toy example data
train_data <- fread('/media/Storage/R/SHAP/RANDOMIZED_train_set_without_Mice_AS_Neuro_p_80.csv')
train_data <- column_to_rownames(train_data, var = "V1")
train_label <- fread('/media/Storage/R/SHAP/RANDOMIZED_train_set_without_Mice_AS_Neuro_labels_p_80.csv')
 
# label to a factor for classification
train_label <- as.factor(train_label$`train_labels[shuffled_numbers, ]`)
train_label <- as.vector(train_label)
split_label<- strsplit(train_label, split = "[-_]")

#retrieve Species
species_label <- unlist(lapply(split_label, function(x) x[1]))
celltype_label <-  unlist(lapply(split_label, function(x) x[3]))
disease_label <-  unlist(lapply(split_label, function(x) x[2]))

rownames(train_data) <- NULL
colnames(train_data) <- NULL
train_data <- as.matrix(train_data)
train_data <- as(train_data, "sparseMatrix")

#encode labels
species_label_num <- as.numeric(factor(species_label))
celltype_label_num <- as.numeric(factor(celltype_label))
disease_label_num <- as.numeric(factor(disease_label))

dim(train_data)
length(species_label_num)
length(celltype_label_num)
length(disease_label_num)

table(species_label_num)
table(celltype_label_num)
table(disease_label_num)


####Testing why hfref so badly performances
#train_data sub by HFrEF and HFpEF
dis_sub <- c("HFrEF")
index <- which(disease_label %in% dis_sub)
length(index)
disease_label_sub <- disease_label[index]
train_data_sub <- train_data[index,]
nrow(train_data_sub)

model_dis <- glmnet(
  x = train_data_sub,  # Input features
  y = disease_label_sub,             # Target labels disease
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)

predict_dis <- predict(model_dis, test_data, type = "class")
table(predict_dis)
test_labels <- read.csv(file = "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/f1_loss_runs_24_06_18/240519_test_labels_binarized.csv", header = FALSE)
test_labels <- data.frame(lapply(test_labels, as.numeric))
colnames(test_labels) <- c('Human', 'Mice','Cardiomyocytes', 'Endothelial', 'Fibroblasts',
                           'Immune.cells', 'Neuro', 'Pericytes', 'Smooth.Muscle','AS', 'HFpEF', 'HFrEF', 'CTRL')

matrix_tmp <- as.data.frame(table(test_labels[,colnames(test_labels) == "AS"]))
matrix_tmp$HFrEF <- as.matrix(table(test_labels[,colnames(test_labels) == "HFrEF"]))[,1]
matrix_tmp$HFpEF <- as.matrix(table(test_labels[,colnames(test_labels) == "HFpEF"]))[,1]
matrix_tmp$CTRL <- as.matrix(table(test_labels[,colnames(test_labels) == "CTRL"]))[,1]
colnames(matrix_tmp) <- c("NO/YES", "AS", "HFrEF", "HFpEF", "CTRL")

####

# Standardize the features and fit the model
model_spec <- glmnet(
  x = train_data,  # Input features
  y = species_label_num,             # Target labels species
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)

model_cell <- glmnet(
  x = train_data,  # Input features
  y = celltype_label_num,             # Target labels cell type
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)

model_dis <- glmnet(
  x = train_data,  # Input features
  y = disease_label_num,             # Target labels disease
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)


#Try the test data set
test_data <- fread('/media/Helios_scStorage/Mariano/NN_Human_Mice/whole_matrix_Seurat_extract/240519_test_set.csv') 
test_data <- column_to_rownames(test_data, var = "V1")

rownames(test_data) <- NULL
colnames(test_data) <- NULL
test_data <- as.matrix(test_data)
test_data <- as(test_data, "sparseMatrix")

predict_spec <- predict(model_spec, test_data, type = "class")
predict_cell <- predict(model_cell, test_data, type = "class")
predict_dis <- predict(model_dis, test_data, type = "class")

# Redefine the one hot encoded representation
spec_labels = c('Human', 'Mice')
celltype_labels = c('Cardiomyocytes', 'Endothelial', 'Fibroblasts', 'Immune.cells', 'Neuro', 'Pericytes','Smooth.Muscle')
disease_labels = c('AS', 'HFpEF', 'HFrEF', 'CTRL') # Assumption of same order in ground truth as always

#map the nhames back to the original label names
predict_spec_nam <- factor(predict_spec, levels = c(1,2), labels = c("Human","Mice"))
predict_cell_nam <- factor(predict_cell, levels = c(1,2,3,4,5,6,7), labels = c("Cardiomyocytes","Endothelial","Fibroblasts",
                                                                               "Immune.cells","Neuro","Pericytes",
                                                                               "Smooth.Muscle"))
predict_dis_nam <- factor(predict_dis, levels = c(1,2,3,4), labels = c("AS","CTRL","HFpEF","HFrEF"))

one_hot_matrix <- matrix(0, nrow = length(predict_spec_nam), ncol = 13)

# Assign column names to the one-hot matrix
colnames(one_hot_matrix) <- test_labels

# Fill the matrix with 1s where appropriate Species
for (i in 1:length(predict_spec_nam)) {
  label <- predict_spec_nam[i]
  
  # Check for each category in the test_labels
  for (j in 1:length(test_labels)) {
    if (grepl(test_labels[j], label)) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Fill the matrix with 1s where appropriate Cell type
for (i in 1:length(predict_cell_nam)) {
  label <- predict_cell_nam[i]
  
  # Check for each category in the test_labels
  for (j in 1:length(test_labels)) {
    if (grepl(test_labels[j], label)) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Fill the matrix with 1s where appropriate Disease
for (i in 1:length(predict_dis_nam)) {
  label <- predict_dis_nam[i]
  
  # Check for each category in the test_labels
  for (j in 1:length(test_labels)) {
    if (grepl(test_labels[j], label)) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Convert to a data frame for easier viewing
one_hot_df <- as.data.frame(one_hot_matrix)

write.csv(one_hot_df, "/media/Helios_scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class/one_hot_encoded_predictions_test_data_LR_multinomial.csv", row.names = F)

saveRDS(model_spec, "/media/Helios_scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class/glmnet_models/Multinomial_LR_whole_train_data_model_SPECIES.Rds")
saveRDS(model_cell, "/media/Helios_scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class/glmnet_models/Multinomial_LR_whole_train_data_model_CELLTYPE.Rds")
saveRDS(model_dis, "/media/Helios_scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class/glmnet_models/Multinomial_LR_whole_train_data_model_DISEASE.Rds")
```

#2. LGR model on autoencoder output for each of the three big groups ( species, disease, cell type)
```{r}
library(glmnet)
library(data.table)
library(tidyverse)

# Load the autoencoder output
train_data <- fread("/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/f1_loss_runs_24_06_18/AE_features_train_5000_2400_350_2200_5150_Batch_10240_SEED_1234_RUN3.csv")

# Load labels
train_label <- fread("/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/Storage_backup/anndata_shap/RANDOMIZED_train_set_without_Mice_AS_Neuro_labels_p_80.csv")

 
# label to a factor for classification
train_label <- as.factor(train_label$`train_labels[shuffled_numbers, ]`)
train_label <- as.vector(train_label)
split_label<- strsplit(train_label, split = "[-_]")

#retrieve Species
species_label <- unlist(lapply(split_label, function(x) x[1]))
celltype_label <-  unlist(lapply(split_label, function(x) x[3]))
disease_label <-  unlist(lapply(split_label, function(x) x[2]))

rownames(train_data) <- NULL
colnames(train_data) <- NULL
train_data <- as.matrix(train_data)
# train_data <- as(train_data, "sparseMatrix")

#encode labels
species_label_num <- as.numeric(factor(species_label))
celltype_label_num <- as.numeric(factor(celltype_label))
disease_label_num <- as.numeric(factor(disease_label))

dim(train_data)
length(species_label_num)
length(celltype_label_num)
length(disease_label_num)

table(species_label_num)
table(celltype_label_num)
table(disease_label_num)


# Standardize the features and fit the model
model_spec <- glmnet(
  x = train_data,  # Input features
  y = species_label_num,             # Target labels species
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)

model_cell <- glmnet(
  x = train_data,  # Input features
  y = celltype_label_num,             # Target labels cell type
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)

model_dis <- glmnet(
  x = train_data,  # Input features
  y = disease_label_num,             # Target labels disease
  family = "multinomial",            # Specify multinomial logistic regression
  alpha = 0.5,                       # Elastic net mixing parameter (0 = l2, 1 = l1)
  lambda = 0.1,                      # Regularization strength, I assume now 0.1 as a default
  standardize = F                 # Standardize features
)


#Try the test data set
test_data <- fread("/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class_AE/AE_encoded_test_set/AUTO_PRED_TEST.csv") 
test_data <- column_to_rownames(test_data, var = "V1")

rownames(test_data) <- NULL
colnames(test_data) <- NULL
test_data <- as.matrix(test_data)
test_data <- as(test_data, "sparseMatrix")

predict_spec <- predict(model_spec, test_data, type = "class")
predict_cell <- predict(model_cell, test_data, type = "class")
predict_dis <- predict(model_dis, test_data, type = "class")

# Redefine the one hot encoded representation
spec_labels = c('Human', 'Mice')
celltype_labels = c('Cardiomyocytes', 'Endothelial', 'Fibroblasts', 'Immune.cells', 'Neuro', 'Pericytes','Smooth.Muscle')
disease_labels = c('AS', 'HFpEF', 'HFrEF', 'CTRL') # Assumption of same order in ground truth as always

#map the nhames back to the original label names
predict_spec_nam <- factor(predict_spec, levels = c(1,2), labels = c("Human","Mice"))
predict_cell_nam <- factor(predict_cell, levels = c(1,2,3,4,5,6,7), labels = c("Cardiomyocytes","Endothelial","Fibroblasts",
                                                                               "Immune.cells","Neuro","Pericytes",
                                                                               "Smooth.Muscle"))
predict_dis_nam <- factor(predict_dis, levels = c(1,2,3,4), labels = c("AS","CTRL","HFpEF","HFrEF"))

one_hot_matrix <- matrix(0, nrow = length(predict_spec_nam), ncol = 13)

# Assign column names to the one-hot matrix
test_labels <- read.csv(file = "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/f1_loss_runs_24_06_18/240519_test_labels_binarized.csv", header = FALSE)
test_labels <- data.frame(lapply(test_labels, as.numeric))
colnames(test_labels) <- c('Human', 'Mice','Cardiomyocytes', 'Endothelial', 'Fibroblasts',
                           'Immune.cells', 'Neuro', 'Pericytes', 'Smooth.Muscle','AS', 'HFpEF', 'HFrEF', 'CTRL')
colnames(one_hot_matrix) <- colnames(test_labels)

# Fill the matrix with 1s where appropriate Species
for (i in 1:nrow(one_hot_matrix)) {
  for (j in 1:ncol(one_hot_matrix)) {
    if (predict_spec_nam[i] == colnames(one_hot_matrix)[j]) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Fill the matrix with 1s where appropriate Cell type
for (i in 1:nrow(one_hot_matrix)) {
  for (j in 1:ncol(one_hot_matrix)) {
    if (predict_cell_nam[i] == colnames(one_hot_matrix)[j]) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Fill the matrix with 1s where appropriate Cell type
for (i in 1:nrow(one_hot_matrix)) {
  for (j in 1:ncol(one_hot_matrix)) {
    if (predict_dis_nam[i] == colnames(one_hot_matrix)[j]) {
      one_hot_matrix[i, j] <- 1
    }
  }
}

# Convert to a data frame for easier viewing
one_hot_df <- as.data.frame(one_hot_matrix)

write.csv(one_hot_df, "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class_AE/one_hot_encoded_predictions_test_data_LR_multinomial.csv", row.names = F)

saveRDS(model_spec, "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class_AE/glmnet_models/Multinomial_LR_whole_train_data_model_SPECIES.Rds")
saveRDS(model_cell, "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class_AE/glmnet_models/Multinomial_LR_whole_train_data_model_CELLTYPE.Rds")
saveRDS(model_dis, "/mnt/mariano/Sequencing_Storage/scStorage/Mariano/NN_Human_Mice/multinomial_logistic_regression_model/new_run_3_major_class_AE/glmnet_models/Multinomial_LR_whole_train_data_model_DISEASE.Rds")
```

